using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using System.Text.Json;

using Amazon.Lambda.Core;
using AutoGenerated;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace Processor
{

    public class Processor
    {

        public async Task<string> FunctionHandler(OrderLine eve, ILambdaContext context)
        {
            Console.WriteLine("Processing event from event bridge");
            Console.WriteLine($"order id {eve.OrderId}, customer id {eve.CustomerId}");
            return "ok";
        }
    }
}
