namespace AutoGenerated
{
    using System;
    using System.Collections.Generic;

    public partial class OrderLine
    {
        public string CustomerId { get; set; }
        public string OrderId { get; set; }
    }
}
