namespace AutoGenerated
{
    using System;
    using System.Collections.Generic;

    public partial class OrderItemAddedEvent
    {
        public string Account { get; set; }
        public ItemAdded Detail { get; set; }
        public string DetailType { get; set; }
        public string Id { get; set; }
        public string Region { get; set; }
        public System.Collections.Generic.List<System.Collections.Generic.Dictionary<string, object>> Resources { get; set; }
        public string Source { get; set; }
        public DateTimeOffset Time { get; set; }
        public string Version { get; set; }
    }

    public partial class ItemAdded
    {
        public string CorelationId { get; set; }
        public string CustomerId { get; set; }
        public string OrderId { get; set; }
        public System.Collections.Generic.List<ItemAddedItem> OrderLines { get; set; }
    }

    public partial class ItemAddedItem
    {
        public double Amount { get; set; }
        public string Id { get; set; }
        public string Type { get; set; }
    }
}
